export const events = [
  {
    id: "me1e1glhpIdvYxCODrgI",
    title: "New Gen Music Festival",
    date: "8/23/2025",
    time: "14:00",
    desc: "Step into the future of sound at the New Gen Music Festival! Experience a groundbreaking showcase of the hottest emerging artists and trailblazing sounds shaping tomorrow's music scene. From pulsating electronic beats to soulful R&B melodies and genre-defying performances, this festival is your chance to discover your new favorite artist. Don't miss the event where the next generation of music takes center stage.",
    venue: "Congress Hall, Main Campus",
    school: "University of Abuja",
    createdBy: "Anslem Emeka",
    bannerUrl: "https://images.pexels.com/photos/3536274/pexels-photo-3536274.jpeg",
    free: true,
    fee: 0,
    createdAt: 1755126000000,
  },
  {
    id: "me1e3mj1YHblCmgFuWH4",
    title: "Innovate Tech Summit 2025",
    date: "9/15/2025",
    time: "09:00",
    desc: "Join top industry leaders and innovators for a day of inspiring talks, hands-on workshops, and networking opportunities. Explore the latest advancements in AI, sustainable technology, and future-forward solutions.",
    venue: "Faculty of Engineering Auditorium",
    school: "University of Lagos",
    createdBy: "The Innovation Hub",
    bannerUrl: "https://images.pexels.com/photos/15765233/pexels-photo-15765233.jpeg",
    free: false,
    fee: 5000,
    createdAt: 1756598400000,
  },
  {
    id: "me1e3wgda3rfkStRXcMI",
    title: "Art & Culture Expo",
    date: "10/05/2025",
    time: "10:00",
    desc: "A vibrant exhibition celebrating local artists, musicians, and performers. Discover unique paintings, sculptures, and traditional crafts, and enjoy live music and dance throughout the day.",
    venue: "Student Union Building",
    school: "Ahmadu Bello University, Zaria",
    createdBy: "Ahmadu Bello University Arts Society",
    bannerUrl: "https://images.pexels.com/photos/33332353/pexels-photo-33332353.jpeg",
    free: true,
    fee: 0,
    createdAt: 1758064800000,
  },
  {
    id: "me1e48jyxmdpArj5v69V",
    title: "Code-a-thon Challenge",
    date: "11/02/2025",
    time: "08:00",
    desc: "Are you up for the challenge? Teams will compete to build innovative solutions to real-world problems in just 24 hours. A great opportunity to test your skills, collaborate, and win amazing prizes.",
    venue: "Computer Science Department Lab",
    school: "University of Port Harcourt",
    createdBy: "Port Harcourt Tech Community",
    bannerUrl: "https://images.pexels.com/photos/27892094/pexels-photo-27892094.jpeg",
    free: true,
    fee: 0,
    createdAt: 1759530000000,
  },
  {
    id: "me1e4jmyde6PdwmJ3LKT",
    title: "Entrepreneurship Masterclass",
    date: "12/01/2025",
    time: "13:00",
    desc: "Learn from successful entrepreneurs and business leaders. This masterclass covers everything from developing a business plan to securing funding and scaling your startup. Ideal for aspiring founders.",
    venue: "Multipurpose Hall, Old Campus",
    school: "Obafemi Awolowo University",
    createdBy: "OAU Entrepreneurship Club",
    bannerUrl: "https://images.pexels.com/photos/29547485/pexels-photo-29547485.jpeg",
    free: false,
    fee: 2500,
    createdAt: 1760989200000,
  },
  {
    id: "me1e4ukc7G9mRsGMzSTc",
    title: "Inter-School Debate Championship",
    date: "1/20/2026",
    time: "11:00",
    desc: "Watch as the best young minds from across the state go head-to-head in a battle of wits and words. Debaters will tackle pressing social, political, and economic issues. A must-see for all.",
    venue: "Senate Building Auditorium",
    school: "University of Abuja",
    createdBy: "Debate & Oratory Society",
    bannerUrl: "https://images.pexels.com/photos/1708987/pexels-photo-1708987.jpeg",
    free: true,
    fee: 0,
    createdAt: 1762886400000,
  },
  {
    id: "me1e57pjTiDkDSc4xVk1",
    title: "Health & Wellness Fair",
    date: "2/10/2026",
    time: "09:30",
    desc: "A day dedicated to your well-being. Get free health screenings, attend fitness classes, and learn about mental health, nutrition, and stress management from experts. All are welcome.",
    venue: "Sports Complex",
    school: "Covenant University",
    createdBy: "Covenant University Medical Directorate",
    bannerUrl: "https://images.pexels.com/photos/33284136/pexels-photo-33284136.jpeg",
    free: true,
    fee: 0,
    createdAt: 1764787200000,
  },
  {
    id: "me1e5ivmsS2g674DSGoN",
    title: "Drama & Theater Night",
    date: "3/15/2026",
    time: "19:00",
    desc: "An evening of powerful storytelling and captivating performances. The drama club presents a new play that explores themes of identity, love, and loss. Prepare to be moved.",
    venue: "Arts Theatre",
    school: "University of Nigeria, Nsukka",
    createdBy: "UNN Drama & Theater Club",
    bannerUrl: "https://images.pexels.com/photos/7991498/pexels-photo-7991498.jpeg",
    free: false,
    fee: 1000,
    createdAt: 1766150400000,
  },
  {
    id: "me1e5qm2u1AiHaJVOOcZ",
    title: "Environmental Awareness Day",
    date: "4/22/2026",
    time: "10:00",
    desc: "Join us in our mission to create a sustainable future. Activities include a campus-wide cleanup, tree planting, and educational talks on climate change and conservation. Let's make a difference together.",
    venue: "Main Campus Green Space",
    school: "Federal University of Technology, Owerri",
    createdBy: "FUTO Environmental Society",
    bannerUrl: "https://images.pexels.com/photos/7475171/pexels-photo-7475171.jpeg",
    free: true,
    fee: 0,
    createdAt: 1768483200000,
  },
  {
    id: "me1e601jaSW9h8Gr8tTB",
    title: "Annual Sportsfest",
    date: "5/10/2026",
    time: "12:00",
    desc: "Cheer for your favorite teams in the biggest sporting event of the year. Featuring basketball, football, track and field, and more. Come for the competition, stay for the camaraderie.",
    venue: "University Stadium",
    school: "University of Benin",
    createdBy: "UNIBEN Sports Council",
    bannerUrl: "https://images.pexels.com/photos/7625429/pexels-photo-7625429.jpeg",
    free: true,
    fee: 0,
    createdAt: 1770038400000,
  },
  {
    id: "me1e692ykW8I2rNsDiqp",
    title: "Career Development Workshop",
    date: "6/18/2026",
    time: "10:00",
    desc: "Prepare for your professional journey with this comprehensive workshop. Topics include resume writing, interview skills, and building a professional network. Gain the tools you need to succeed.",
    venue: "Conference Centre",
    school: "University of Ibadan",
    createdBy: "UI Career Services",
    bannerUrl: "https://images.pexels.com/photos/8761349/pexels-photo-8761349.jpeg",
    free: false,
    fee: 1500,
    createdAt: 1771840800000,
  }
]